name: Trigger repo
on:
  push:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build in site repo
        env:
          REPO: bitcoinlulz/bitcoin.holiday
          WORKFLOW_FILENAME: git_action.yaml
        run: |
          curl -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GH_PRIVATE_REPO_ACCESS_TOKEN }}" \
            "https://api.github.com/repos/${REPO}/actions/workflows/${WORKFLOW_FILENAME}/dispatches" \
            -d '{ "ref": "main" }'
